"""new fields in user model

Revision ID: 077619f9c2a4
Revises: 4b4fd58e99d2
Create Date: 2018-10-10 21:17:54.753548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077619f9c2a4'
down_revision = '4b4fd58e99d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
